apiVersion: v1
kind: ReplicationController
metadata:
  name: merlink8s-named-port-rc
spec:
  replicas: 3
  selector:
    app: merlink8s-named-port-rc-simple
  template:
    metadata:
      labels:
        app: merlink8s-named-port-rc-simple
    spec:
      containers:
        - name: merlink8s-named-port-rc-container
          image: ctang1989/simple-nodejs-http-server:1.0.0
          ports:
          - name: http
            containerPort: 8090
