apiVersion: apps/v1
kind: Deployment
metadata:
  name: merlink8s-deployment
  labels:
    app: merlink8s-deployment-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: merlink8s-deployment-nginx
  template:
    metadata:
      labels:
        app: merlink8s-deployment-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
