apiVersion: batch/v1
kind: Job
metadata:
  name: merlink8s-multi-completion-parallel-job
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        app: merlink8s-multi-completion-parallel-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: ctang1989/merlin-k8s-batch-job:v0.1.0
