apiVersion: batch/v1
kind: CronJob
metadata:
  name: merlink8s-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: merlink8s-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: ctang1989/batch-job:1.0.0
