apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: merlink8s-daemonset
spec:
  selector:
    matchLabels:
      app: merlink8s-daemonset
  template:
    metadata:
      labels:
        app: merlink8s-daemonset
    spec:
      nodeSelector:
        disk: ssd
      containers:
        - name: main
          image: ctang1989/simple-nodejs-http-server:1.0.0
