apiVersion: v1
kind: Service
metadata:
  name: merlink8s-multi-named-ports-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8090
  - name: https
    port: 443
    targetPort: 8090
  selector:
    app: merlink8s-rc-simple
