apiVersion: v1
kind: Service
metadata:
  name: merlink8s-session-affinity-svc
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: merlink8s-rc-simple
